@startuml

actor User as U
participant WebApp as WA 
participant "Web Server Manager" as AM
participant Controller as D

U -> WA: triggers event event
activate D
activate AM
activate WA
WA -> AM : API call with token
AM -> AM : Check token
alt valid
    AM -> D : Interface call
    D -> AM : Response
    AM -> WA : Response
    WA -> U : Response
else invalid
    AM -> WA : Non authorized error
    WA -> U : Non authorized error
end
deactivate WA
deactivate AM

@enduml