@startuml

autonumber

actor Student as U
participant emailProvider as EP
participant TournamentManager as TM
participant BadgeManager as BM
participant EvaluationManager as EM
participant RMPManager as RMP
participant NotificationManager as NM
participant StudentManager as SM
participant DBMSManager as DB

activate DB
activate TM
activate EP
TM -> TM: tournamentEnded()
loop for each Badge
    TM -> BM: evaluateCriteria(Badge)
    activate BM
    BM -> EM: evaluateCriterium(Crterium, Tournament)
    activate EM
    alt if necessary, for each Team repo
        EM -> RMP: pull(repo)
        activate RMP
        RMP --> EM: code
        deactivate RMP
    end
    EM --> BM: eligibleStudents
    deactivate EM
    alt if eligibleStudents is not empty
        loop for each eligible student
            BM -> SM: assignBadge(Student, Badge)
            activate SM
            SM -> DB: query(assignBadge, student, badge)
            DB --> SM: success
            SM --> BM: success
            deactivate SM
            BM -> NM: sendNotification(Student, Details)
            activate NM
            NM -> EP: sendEmail(Student, Details)
            deactivate NM
            EP -> U: receiveEmail
        end
    end
    deactivate BM
end
deactivate TM
deactivate DB
deactivate EP

@enduml