@startuml

autonumber
actor Educator as U
participant WebServerModule as WS
participant Controller as C
participant BadgeManager as BM
participant NotificationManager as NM
participant EmailProvider as EP

activate U
U->WS: POST /api/createBadge
activate WS
WS->C: createBadge(badgeData): Boolean
activate C
C->BM: createBadge(badgeData): Boolean
BM-->C: True (badge created)
C-->WS: True (badge created)
deactivate WS
C->NM: sendNotification(email: String, text: String):Boolean
activate NM
NM->EP:send email
activate EP
NM-->C: True (email successfully sent)
deactivate NM
deactivate C
EP->U: reads email

@enduml