@startuml

'NEW:w
autonumber
actor Educator as E
participant "RMP Platform" as RMP
participant "Email Provider" as EM 
participant "Web Server Module" as WS
participant Controller as C
participant TournamentManager as TM
participant NotificationManager as NM
participant DBMSManager as DB 

E -> RMP: create new repository
activate RMP
RMP --> E
deactivate RMP
E -> WS: /POST/createBattle
activate WS
WS -> C: createBattle(battleData: battleData)
activate C
C -> TM: addNewBattle(battleData: battleData)
activate TM
alt right Tournament state
    TM -> DB: query(Query: string, battleData)
    activate DB
    DB --> TM: ok
    deactivate DB
    TM -> NM: sendNotification(Email: string, Text: text)
    activate NM
    NM -> EM: send email
    activate EM
    EM -> E: receive email
    deactivate EM
    NM --> TM: ok
    deactivate NM
    TM --> C: ok
    C --> WS: ok
    deactivate C
    WS -> E: Battle detail page
    deactivate WS
else tournament state is wrong 
    TM -> NM: sendNotification(Email: string, Text: string)
    activate NM
    NM -> EM: send email
    deactivate NM
    activate EM
    EM -> E: receive email
    deactivate EM
end
@enduml