@startuml

'NEW:w
autonumber
actor Educator as E
participant "RMP Platform" as RMP
participant "Email Provider" as EM 
participant "Web Server Module" as WS
participant Controller as C
participant TournamentManager as TM
participant NotificationManager as NM
participant DBMSManager as DB 

activate E
E -> RMP: create new repository
activate RMP
RMP --> E
deactivate RMP
E -> WS: /POST/createBattle
activate WS
WS -> C: addNewBattle(battleData: battleData): Boolean
activate C
C -> TM: addNewBattle(battleData: battleData): Boolean
activate TM
alt right Tournament state
    TM -> DB: query(Query: string, args: List<String>): QueryResult
    activate DB
    DB --> TM: QueryResult
    deactivate DB
    TM -> NM: sendNotification(Notification: Notification): Void
    activate NM
    NM -> EM: send email
    deactivate NM
    activate EM
    EM -> E: receive email
    deactivate EM
    TM --> C: True (Battle Created)
    C --> WS: True (Battle Created)
    deactivate C
    WS -> E: Battle detail page
    deactivate WS
else tournament state is wrong 
    TM -> NM: sendNotification(Notification: Notification): Void
    deactivate TM
    activate NM
    NM -> EM: send email
    deactivate NM
    activate EM
    EM -> E: receive email
    deactivate EM
end
@enduml
