@startuml

'NEW
autonumber
actor Educator as E
actor Student as S
participant EmailProvider as EM
participant "Web Server Module" as WS
participant Controller as C
participant TournamentManager as TM
participant NotificationManager as NM
participant DBMSManager as DB

activate E
activate WS
E -> WS: get form
WS -> E: show form
E -> WS: POST /api/createTournament
WS -> C: createTournament(TournamentData: TournamentData): Boolean
activate C
C -> TM: createTournament(TournamentData: TournamentData): Boolean
activate TM
TM -> DB: query(Query: String, args: List<String>): QueryResult
activate DB
DB -> TM: QueryResult
deactivate DB
TM -> NM: sendNotification(Notification: Notification): Void
activate NM
TM -> C: True (Tournament created)
deactivate TM
C -> WS: True (Tournament created)
deactivate C
WS -> E: Tournament Detail Page
loop for each student
NM -> EM: send Email
deactivate NM
activate EM
EM -> S: Read Email
deactivate EM
end

@enduml
