@startuml

'NEW
autonumber
actor Educator as E
actor Student as S
participant EmailProvider as EM
participant "Web Server Module" as WS
participant Controller as C
participant TournamentManager as TM
participant NotificationManager as NM
participant DBMSManager as DB

activate WS
E -> WS: get form
WS -> E: show form
E -> WS: POST /api/createTournament
WS -> C: createTournament(TournamentData: TournamentData)
activate C
C -> TM: createTournament(TournamentData: TournamentData)
activate TM
TM -> DB: query(Query: string, TournamentData: TournamentData)
activate DB
DB -> TM: ok
deactivate DB
TM -> NM: sendTournamentNotification(TournamentData: TournamentData)
activate NM
TM -> C: ok
deactivate TM
C -> WS: ok
deactivate C
WS -> E: Tournament Detail Page
loop for each student
NM -> EM: send Email
deactivate NM
activate EM
EM -> S: Read Email
deactivate EM
end

@enduml