@startuml

autonumber
participant GenericComponent as C
participant CompoentA as A
participant Dispatcher as D
participant ComponentB as B

activate A
activate B
activate D

A -> D: getData(microserviceName: string)
D --> A: microserviceData: microserviceData
A -> B: interfaceCall
B --> A: response

@enduml
