@startuml

autonumber
participant Somewhere as C
participant MicroserviceA as A
participant Dispatcher as D
participant MicroserviceB as B

activate A
activate B
activate C
activate D

C --> A: Some call of some procedure
deactivate C
A -> D: getData(microserviceName: string)
D --> A: microserviceData: microserviceData
A -> B: interfaceCall
B --> A: response

@enduml
