@startuml

autonumber

participant EvaluationManager as EM
participant BattleManager as BM
participant TournamentManager as TM
participant RMPManager as RMP

activate RMP
RMP -> EM: newCodeAvailable(repo: Repo): Void
activate EM
EM -> RMP: pullRequest(repo: Repo): Array<File>
RMP --> EM: Array<File>
deactivate RMP
EM -> EM: evaluate code
EM -> BM: updateBattleScore(team: Team, score: Score): Void
deactivate EM
activate BM
BM -> TM: updateTournamentScore(team: Team, score: Score): Void
deactivate BM

@enduml