@startuml

autonumber

actor Student as S
participant EmailProvider as EP
participant WebServerModule as WS
participant Controller as C
participant Dispatcher as MD
participant TournamentManager as TM
participant NotificationManager as NM
participant DBMSManager as DBMSM

activate S
S -> WS: GET /api/tournamentData
activate WS
WS -> C: getTournamentData(tournament:\n String): Tournament
activate C
C -> MD: getTournamentData(tournament:\n String): Tournament
activate MD
MD -> DBMSM: getTournamentData(tournament: String): Tournament
activate DBMSM
DBMSM --> MD: Tournament
deactivate DBMSM
MD --> C: Tournament
deactivate MD
C --> WS: Tournament
deactivate C
WS --> S: Tournament
deactivate WS
S -> WS: POST /api/joinTournament
activate WS
WS -> C: createTeam(tournament: String,\n email: String,\n team: String): Tournament Page
activate C
C -> MD: createTeam(tournament: String,\n email: String,\n team: String): Tournament Page
activate MD
MD -> TM: createTeam(tournament: String,\n email: String,\n team: String): Tournament Page
activate TM
TM -> DBMSM: searchTeamTournament(team: String,\n tournament: String): Team
activate DBMSM
DBMSM --> TM: Team
deactivate DBMSM
alt if Team is NULL
    TM -> DBMSM: createTeam(tournament: String,\n team: String): Void
    activate DBMSM
    DBMSM -> DBMSM: Insert\nteam in\ntournament
    DBMSM --> TM: OK
    deactivate DBMSM
    TM -> DBMSM: addStudentToTeam(tournament: String,\n team: String, email: String): Void
    activate DBMSM
    DBMSM -> DBMSM: Insert\nstudent in\nteam
    DBMSM --> TM: OK
    deactivate DBMSM
    TM -> NM: sendNotification(email: String,\n text: String): Void
    activate NM
    NM -> EP: email with text
    deactivate NM
    activate EP
    EP -> S: email\n <<subscritpion confirmation>>
    deactivate EP
    TM --> MD: Tournament Page
    deactivate TM
    MD --> C: Tournament Page
    deactivate MD
    C --> WS: Tournament Page
    deactivate C
    WS --> S: Tournament Page
    deactivate WS
else if Team is NOT NULL
    TM -> MD: Exception: Team already exists
    activate MD
    MD -> C: Exception: Team already exists
    deactivate MD
    activate C
    C -> WS: Exception: Team already exists
    deactivate C
    activate WS
    WS -> S: Exception: Team already exists
    deactivate WS
end

@enduml