@startuml

autonumber

actor User as U
participant WebServerModule as WS
participant Controller as C
participant LoginManager as LM
participant AccountManager as AM
participant DBMSManager as DBMSM

activate U
U -> WS: POST /api/logIn
activate WS
WS -> C: logIn(logInData: LogInData): Session
activate C
C -> LM: logIn(logInData: LogInData): Session
activate LM
LM -> DBMSM: query(query: String, args: List<String>): QueryResult
note right
    check if email 
    and password 
    match
end note
activate DBMSM
DBMSM --> LM: QueryResult
deactivate DBMSM
alt if QueryResult is not NULL
    LM -> AM: createSession(user: User): Session
    activate AM
    AM --> LM: Session
    deactivate AM
    LM --> C: Session
    deactivate LM
    C --> WS: Session
    deactivate C
    WS --> U: User homepage
    deactivate WS
    deactivate U
else if QueryResult is NULL
    LM --> C: Exception: Invalid email or password
    activate C
    C --> WS: Exception: Invalid email or password
    deactivate C
    activate WS
    WS --> U: Exception: Invalid email or password
    deactivate WS
end

@enduml