@startuml

autonumber

actor "Invited Educator" as U2
participant EmailProvider as EP
participant WebServerModule as WS
participant Controller as C
participant TournamentManager as TM
participant NotificationManager as NM
participant DBMSManager as DBMS

activate U2
alt Educator accepts Invitation
    U2 -> WS: POST /api/confirm
    deactivate U2
    activate WS
    WS -> C: receiveResponse(response: Response): Void
    deactivate WS
    activate C
    C -> NM: receiveResponse(response: Response): Void
    deactivate C
    activate NM
    NM -> TM: joinEducator(educator: Educator,\n tournament: Tournament): Void
    deactivate NM
    activate TM
    TM -> DBMS: query(query: String, args: List<String>): QueryResult
    activate DBMS
    note right
        add Educator 
        to Tournament
    end note
    DBMS --> TM: QueryResult
    deactivate DBMS
    deactivate TM
else Educator refuses Invitation
end

@enduml