@startuml

actor "Invited Educator" as E
participant "Email Provider" as EM
participant "Web Server Module" as WS
participant Controller as C
participant "Torunament Manager" as TM 
participant "DBMS Manager" as DB

TM -> EM: send email with link
EM -> E: read email
alt click on the confirmation link
    E -> WS: POST /api/confirm
    activate WS
    WS -> C: confirmEducatorInvitation(Tournament: string, Educator: string)
    activate C
    C -> TM: confirmEducatorInvitation(Tournament: string, Educator: string)
    activate TM
    TM -> DB: addTournamentManager(Tournament: string, Educator: string)
end

@enduml