@startuml

' NEW
autonumber
actor "Invited Student" as S
participant "Email Provider" as EM
participant "Web Server Module" as WS
participant Controller as C
participant "Torunament Manager" as TM 
participant "DBMS Manager" as DB

TM -> EM: send email with link
EM -> S: read email
alt click on the confirmation link
    S -> WS: POST /api/confirm
    activate WS
    WS -> C: confirmStudentInvitation(Tournament: string, Student: string, TeamName: string)
    activate C
    C -> TM: confirmEducatorInvitation(Tournament: string, Student: string, TeamName: string)
    activate TM
    TM -> DB: query(Query: String, Tournament: string, Student: string, TeamName: string)
end

@enduml