@startuml

autonumber

actor User as U
participant EmailProvider as EP
participant WebServerModule as WS
participant Controller as C
participant SignInManager as SIM
participant NotificationManager as NM
participant DBMSManager as DBMSM

activate U
U -> WS: POST /api/signIn
activate WS
WS -> C: signIn(signInData: SignInData): Void
activate C
C -> SIM: signIn(signInData: SignInData): Void
activate SIM
SIM -> DBMSM: query(query: String, args: List<String>): QueryResult
note right
    check if 
    credentials
    are not 
    already used
end note
activate DBMSM
DBMSM --> SIM: QueryResult
deactivate DBMSM
alt QueryResult is NULL
    SIM -> NM: sendNotification(notification: Notification): Void
    activate NM
    SIM --> C: True (confirmation mail sent)
    deactivate SIM
    C --> WS: True (confirmation mail sent)
    deactivate C
    WS --> U: Page: <<confirmation mail sent>>
    deactivate WS
    NM -> EP: send email with text
    deactivate NM
    activate EP
    EP -> U: email <<confirmation email>>
    deactivate EP
    U -> WS: POST /api/confirm
    activate WS
    WS -> C: receiveResponse(response: Response): Boolean
    deactivate WS
    activate C
    C -> NM: receiveResponse(response: Response): Boolean
    deactivate C
    activate NM
    NM -> SIM: createAccount(email: String): Void
    deactivate NM
    activate SIM
    SIM -> DBMSM: query(query: String, args: List<String>): QueryResult
    activate DBMSM
    DBMSM --> SIM: QueryResult
    deactivate DBMSM
    deactivate SIM
else QueryResult is not NULL
    SIM --> C: Exception: email/RMPHandle already exists
    activate C
    C --> WS: Exception: email/RMPHandle already exists
    deactivate C
    activate WS
    WS --> U: Exception: email/RMPHandle already exists
    deactivate WS
end

@enduml