@startuml

autonumber
actor Student as U
participant searchManager as SM
participant WebServerModule as WS
participant Controller as C
participant searchMangaer as SM
participant DBMSMangaer as DBMS

activate U
U->WS: GET /api/search
activate WS
WS->C: searchTournament(searchQuery: String): Array<tournamentData>
activate C 
C->SM: searchTournament(searchQuery: String): Array<tournamentData>
activate SM
SM->DBMS: query(query: String, args List<String>): QueryResult
activate DBMS
DBMS-->SM: QueryResult
deactivate DBMS
SM-->C: Array<tournamentData>
deactivate SM
C-->WS: Array<tournamentData>
deactivate C
WS->U: read tournaments available



@enduml