@startuml

autonumber
actor Student as U
participant searchManager as SM
participant WebServerModule as WS
participant Controller as C
participant searchMangaer as SM
participant DBMSMangaer as DBMS

activate U
U->WS: GET /api/search
WS->C: searchTournament(searchQuery: String): Array<tournamentData>
activate WS 
C->SM: searchTournament(searchQuery: String): Array<tournamentData>
activate C
SM->DBMS: query(query: String, args List<String>): QueryResult
activate SM
DBMS-->SM: QueryResult
SM-->C: Array<tournamentManager>
deactivate SM
C-->WS: Array<tournamentManager>
deactivate C
WS->U: read tournaments available



@enduml