@startuml

autonumber

actor Educator as U
participant WebServerModule as WS
participant Controller as C
participant searchManager as SM
participant TournamentManager as TM


U->WS: POST /api/addScore
activate WS
WS->C: updateTournamentScore(Team: String, Score: int, tournamentName: String): void
activate C
C->SM: searchTournament(tournamentName: String, properties: Array<String>): Array<TournamentManager>
activate SM
SM-->C: Array<TournamentManager>
deactivate SM
C-> TM: updateTournamentScore(Team: String, Score, int): void
deactivate C

@enduml