@startuml

autonumber
actor Student as U
participant searchManager as SM
participant WebServerModule as WS
participant Controller as C
participant searchMangaer as SM
participant DBMSMangaer as DBMS

activate U
U->WS: GET /api/search
activate WS
WS->C: searchUser(searchQuery: String): Array<UserData>
activate C 
C->SM: searchUser(searchQuery: String): Array<UserData>
activate SM
SM->DBMS: query(query: String, args List<String>): QueryResult
activate DBMS
DBMS-->SM: QueryResult
deactivate DBMS
SM-->C: Array<UserData>
deactivate SM
C-->WS:Array<UserData>
deactivate C
WS->U: read Users information



@enduml