@startuml

autonumber
actor Student as U
participant searchManager as SM
participant WebServerModule as WS
participant Controller as C
participant searchMangaer as SM
participant DBMSMangaer as DBMS

activate U
U->WS: GET /api/search
WS->C: searchUser(email: String, name: String, surname: String, rmpHandle: String): Array<AccountManager>
activate WS 
C->SM: searchUser(email: String, name: String, surname: String, rmpHandle: String): Array<AccountManager>
activate C
SM->DBMS: query(query: String, args List<String>): QueryResult
activate SM
DBMS-->SM: QueryResult
SM-->C: Array<accountManager>
deactivate SM
C-->WS:Array<accountManager>
deactivate C
WS->U: read Users information



@enduml