@startuml ClientServerParadigm
!include <tupadr3/common>

!define ICONURL https://raw.githubusercontent.com/Roemer/plantuml-office/master/office2014
!includeurl ICONURL/Devices/device_mac_client.puml
!includeurl ICONURL/Servers/server_generic_blue.puml

OFF_DEVICE_MAC_CLIENT(client, Client)
OFF_SERVER_GENERIC_BLUE(server, Server)

client -right-> server
server -left-> client

@enduml

