@startuml

component Client <<subsystem>> #Red{
    component "Web Browser"
}

component "Web Server" as w <<subsystem>> #LightBlue{
    component "Web Server Module"  
}

interface "Web Interface"

'[Web Browser] --> [Web Interface]
'[Web Interface] - [Web Server Module]

component "Application Server" as AppServer <<subsystem>> #LightGreen{
    component "Sign In Manager"
    component "Log In Manager"
    component "RMP Manager"
    component "Notification Manager"
    component "Evaluation Manager"
    component "Badge Manager"
    component "Battle Manager"
    component "Tournament Manager"
    component "Account Manager"
    component "Search Manager"
    component "Dispatcher"
    component "DBMS Manager"
    component "Controller"
}
'[Sign In Manager] -[hidden]- [Log In Manager]
'[Log In Manager] -[hidden]- [RMP Manager]
'[RMP Manager] -[hidden]- [Notification Manager]
'[Notification Manager] -[hidden]- [Dispatcher]
'[Dispatcher] -[hidden]- [Evaluation Manager]
'[Evaluation Manager] -[hidden]- [Badge Manager]
'[Badge Manager] -[hidden]- [Battle Manager]
'[Battle Manager] -[hidden]- [Tournament Manager]
'[Tournament Manager] -[hidden]- [Account Manager]
'[Account Manager] -[hidden]- [Search Manager]
'[DBMS Manager] -[hidden]- [Sign In Manager]

interface "Sign In Interface"
'[Sign In Interface] - [Sign In Manager]
interface "Log In Interface"
'[Log In Interface] - [Log In Manager]
interface "RMP Interface"
'[RMP Interface] - [RMP Manager]
interface "Notification Interface"
'[Notification Interface] - [Notification Manager]
interface "Evaluation Interface"
'[Evaluation Interface] - [Evaluation Manager]
interface "Badge Interface"
'[Badge Interface] - [Badge Manager]
interface "Battle Interface"
'[Battle Interface] - [Battle Manager]
interface "Tournament Interface"
'[Tournament Interface] - [Tournament Manager]
interface "Account Interface"
'[Account Interface] - [Account Manager]
interface "Search Interface"
'[Search Interface] - [Search Manager]
interface "Dispatcher Interface"
'[Dispatcher] - [Dispatcher Interface]
interface "DBMSM Interface"
'[DBMSM Interface] - [DBMS Manager]
interface "Controller Interface"

'[Sign In Interface] -- [Log In Interface]
'[Log In Interface] -- [RMP Interface]
'[RMP Interface] -- [Notification Interface]
'[Notification Interface] -- [Dispatcher Interface]
'[Dispatcher Interface] -- [Evaluation Interface]
'[Evaluation Interface] -- [Badge Interface]
'[Badge Interface] -- [Battle Interface]
'[Battle Interface] -- [Tournament Interface]
'[Tournament Interface] -- [Account Interface]
'[Account Interface] -- [Search Interface]
'[DBMSM Interface] -- [Sign In Interface]


'[Web Server Module] -> [Dispatcher Interface]

component "DBMS Server" as d <<subsystem>> #Violet{
    component DBMS
}

interface "DBMS Interface"
'[DBMS] - [DBMS Interface]
'[DBMS Interface] - [DBMSM Interface]



component "External Services" as es #Cyan{
    component RMP
    component "Email Provider"
}
'RMP -[hidden]- [Email Provider]


'[Email Provider] <- [Notification Interface]
'[RMP] <- [RMP Interface]


'es -[hidden] AppServer
'd -[hidden] AppServer
'w -[hidden]- es
'd -[hidden]--- w
'Client -[hidden]- w



@enduml