@startuml
!include <tupadr3/common>

!define ICONURL https://raw.githubusercontent.com/Roemer/plantuml-office/master/office2014
!includeurl ICONURL/Devices/device_mac_client.puml
!includeurl ICONURL/Servers/server_generic_blue.puml
!includeurl ICONURL/Databases/database_server.puml
!includeurl ICONURL/Services/user_services.puml
!includeurl ICONURL/Users/user_store.puml
!includeurl ICONURL/Services/central_management_service.puml
!includeurl ICONURL/Concepts/settings.puml
!includeurl ICONURL/Services/email_service.puml
!includeurl ICONURL/Communications/3rd_party_service.puml
!includeurl ICONURL/Servers/web_server.puml
!includeurl ICONURL/Concepts/firewall.puml
!includeurl ICONURL/Servers/application_server.puml
!includeurl ICONURL/Concepts/settings_office_365.puml
!includeurl ICONURL/Databases/database.puml
!includeurl ICONURL/Servers/3rd_party_mail_server.puml



package "Client" as clientp{
    OFF_3RD_PARTY_SERVICE(rmp, RMP)
    OFF_DEVICE_MAC_CLIENT(client, Client)
    OFF_3RD_PARTY_MAIL_SERVER(mailServer, Mail Server)
}

package "Application Layer" as apl {
    package "Data Layer" as DataLayer <<Frame>> {
        OFF_DATABASE_SERVER(dbms, DBMS)
        OFF_DATABASE(database, Database)
    }
    package "Inner Application Layer" as InnerApplicationLayer <<Frame>> {
        package Microservices as Microservices <<Frame>> {
            OFF_USER_SERVICES(login, Log In)
            OFF_USER_SERVICES(signin, Sign In)
            OFF_USER_SERVICES(account_mgr, Account Manager)
            OFF_CENTRAL_MANAGEMENT_SERVICE(DBMSManager, DBMSManager)
            OFF_SETTINGS(tournamentMgr, Tournament Manager)
            OFF_SETTINGS(battleMgr, Battle Manager)
            OFF_SETTINGS(badgeMgr, Badge Manager)
            OFF_SETTINGS(evaluationMgr, Evaluation Manager)
            OFF_SETTINGS(searchMgr, Search Manager)
            OFF_SETTINGS(rmpMgr, RMP Manager)
            OFF_EMAIL_SERVICE(notificationMgr, Notification Manager)
        }
        OFF_SETTINGS_OFFICE_365(dispatcher, Microservice Dispatcher)
    }
    package "DMZ" as DMZ <<Frame>> {
        OFF_WEB_SERVER(webServer, Web Server)
    }
}

rmp -right-> webServer
client -right-> webServer
mailServer -right-> webServer
webServer -right-> dispatcher
dispatcher -left-> login
dispatcher -left-> signin
dispatcher -right-> account_mgr
dispatcher -right-> DBMSManager
dispatcher -right-> tournamentMgr
dispatcher -right-> battleMgr
dispatcher -right-> badgeMgr
dispatcher -right-> evaluationMgr
dispatcher -right-> searchMgr
dispatcher -right-> rmpMgr
dispatcher -right-> notificationMgr
DBMSManager -down-> dbms
dbms -right-> database

'stiling 
mailServer -[hidden]down-> rmp
rmp -[hidden]down-> client
notificationMgr -[hidden]down-> DBMSManager
rmpMgr -[hidden]down-> searchMgr
rmpMgr -[hidden]down--> evaluationMgr
evaluationMgr -[hidden]down-> badgeMgr
badgeMgr -[hidden]down-> battleMgr
tournamentMgr -[hidden]down-> DBMSManager
DBMSManager -[hidden]down-> account_mgr
account_mgr -[hidden]down-> signin
signin -[hidden]down-> login
login -[hidden]down-> dispatcher

InnerApplicationLayer -[hidden]right-> DataLayer
DMZ -[hidden]right-> InnerApplicationLayer
DMZ -[hidden]down-> apl
clientp -[hidden]up-> DMZ

@enduml