@startuml entityClassDiagram

scale 1024 width
scale 768 height

skinparam linetype polyline
'Hide circles defaultly present on the classes
hide RMP circle
hide Platform circle
hide User circle
hide Tournament circle
hide Student circle
hide Battle circle
hide Educator circle
hide Badge circle
hide Score circle
hide Team circle

'Define relations
Platform "1" ---> "1" RMP : associated to

Platform "1" --d-> "0...n" Tournament : containts

Tournament "1" o--d-- "0...n" Battle : belongs to 

Platform "1" --d-> "0...n" User

User <|--d-- Student

User <|--d-- Educator

Badge "0...n" --u--> "1" Student : wins

Badge --u--> "1" Educator : creates

Score "1" --u--> "1" Team : assigned to

Student "1...n" o-d--> "1" Team : belongs to

Platform "1" -d---> "1" Score : calculates
@enduml