@startuml entityClassDiagram
skinparam linetype polyline
'Hide circles defaultly present on the classes

'component RMP 
'component Platform 
'component User 
'component Tournament 
'component Student
'component Battle 
'component Educator 
'component Badge 
'component Score 
'component Team 

hide RMP circle
hide Platform circle
hide User circle
hide Tournament circle
hide Student circle
hide Battle circle
hide Educator circle
hide Badge circle
hide Score circle
hide Team circle

'Define relations>
Platform "1" --up-> "1" RMP : associated to

Platform "1" --right--> "0...n" Tournament : containts

Tournament "1" o-down-- "0...n" Battle : belongs to 

Platform "1" -down--> "0...n" User

User <|--down-- Student

User <|--down-- Educator

Badge "0...n" --left--> "1" Student : wins

Educator --left--> "1" Badge : creates

Score "1" -down--> "1" Team : assigned to

Student "1...n" o--up--> "1" Team : belongs to

Platform "1" --left--> "1" Score : calculates
@enduml