@startuml entityClassDiagram
skinparam linetype polyline
'Hide circles defaultly present on the classes

'component RMP 
'component Platform 
'component User 
'component Tournament 
'component Student
'component Battle 
'component Educator 
'component Badge 
'component Score 
'component Team 

hide RMP circle
hide Platform circle
hide User circle
hide Tournament circle
hide Student circle
hide Battle circle
hide Educator circle
hide Badge circle
hide Score circle
hide Team circle

'Define relations>
Battle "1" -right-> "1" RMP : associated to

Platform "1" -right-> "0...n" Tournament : contains

Tournament "1" o-down- "1...n" Battle : belongs to 

Platform "1" -down-> "0...n" User : has

User <|-- Student

User <|-- Educator

Badge "0...n" <-left- "0...n" Student : achieve

Educator "1" -left-> "0...n" Badge : creates

Score "1" -down--> "1" Team : assigned to

Student "1...n" -left-o "1" Team : belongs to

Platform "1" -left-> "1" Score : calculates
@enduml