@startuml entityClassDiagramGamification
'skinparam linetype polyline
'Hide circles defaultly present on the classes

'component Platform 
'component User 
'component Tournament 
'component Student
'component Educator 
'component Badge 
'component Team 

hide Platform circle
hide User circle
hide Tournament circle
hide Student circle
hide Educator circle
hide Badge circle
hide Team circle

'Define relations>

Platform "1" --> "0...n" Tournament : contains
Platform "1" --> "0...n" User : has

User <|-left- Student
User <|-down- Educator

Student "1...n" -left-o "1" Team : belongs to
Student "0...n" -down-> "0...n" Badge : achieve

Educator "1" -left-> "0...n" Badge : creates
Educator --> Tournament : manages

Tournament -right-> Badge : has

Team -down-> Tournament : partecipates to
@enduml