@startuml entityClassDiagramPlatform
'skinparam linetype polyline
'Hide circles defaultly present on the classes

'component Platform 
'component User 
'component Tournament 
'component Student
'component Battle 
'component Educator 
'component Score 
'component Team 

hide Platform circle
hide User circle
hide Tournament circle
hide Student circle
hide Battle circle
hide Educator circle
hide Score circle
hide Team circle

'Define relations>


Platform "1" -right-> "0...n" Tournament : contains
Platform "1" -left-> "1" Score : calculates
Platform "1" -down-> "0...n" User : has

User <|-down- Student
User <|-down- Educator

Student "1...n" -down-o "1" Team : belongs to

Educator -right-> Score : assigns
Educator -right-> Tournament : manages
Educator -right-> Battle : creates

Tournament "1" o-down- "1...n" Battle : belongs to 

Team -down-> Tournament : partecipates to
Team -down-> Score : has

Score -down-> Battle : corresponds to

Score "1" --> "1" Team : assigned to
@enduml