@startuml
package "CKBWebApp"{
    package "Browser"
    Browser ---> DataAccess
    [clientFunctions] -> Browser: use
    component clientFunctions
}

package "CKBServer"{
    database "DBMS"
    [listener] - DataAccess
    [comunicationHandler] ---> listener: use
    [securityHandler] ---> comunicationHandler: use
    [currentLoggedInUsers] ---> securityHandler: use
    [dispatcher] ---> currentLoggedInUsers: use
    UserDataProvider - [dispatcher]
    Send - [emailHandler]
    [currentLoggedInUsers] ---> Send: use
    [emailHandler] ---> DBMS: use
    [RMPHandler] - Pull
    [RMPHandler] ---> DBMS: use
    
    component dispatcher
    component currentLoggedInUsers
    component securityHandler
    component comunicationHandler
    component emailHandler
    component listener
    component RMPHandler

    package "Model"{
        
        [searchManager] ---> UserDataProvider: use
        [battleManager] ---> UserDataProvider: use
        [teamManager] ---> UserDataProvider: use
        [tournamentManager] ---> UserDataProvider: use
        [evaluator] ---> Pull
        
        [searchManager] ---> DBMS: use
        [teamManager] ---> UserDataProvider: use
        [tournamentManager] ---> DBMS: use
        [evaluator] ---> DBMS: updates
        [evaluator] ---> tournamentManager: updates
        [evaluator] ---> battleManager: updates

        [battleManager] ---> tournamentManager: use

        [teamManager] ---> battleManager: use
        component teamManager
        component battleManager
        component tournamentManager
        component searchManager
        component evaluator
    }
}

@end