@startuml
actor Team as T
participant CKBWebApp as A
entity CKBPlatform as P
participant RMP as R

T-->R: pushes code
activate R
R-->P: notifies repository update occurred
activate P
P-->P: controls Team-Repository correspondence 
P-->P: Tests enviroment setup
group if repository not associated with any Team
    P-->P: clean up Tests enviroment
else
    activate P
    deactivate P
    P-->R: requires corresponding Team code from repository 
    P<--R: pulls code 
    deactivate R
    P-->P: runs Tests on pulled code in the enviroment 
    activate P
    deactivate P
    P-->P: assignes Score to the Team
    P-->P: updates Tournament ranking
    P->A: new Team Score available 
    activate A
    P->A: new Tournament ranking available
    deactivate P
    T<--A: new Score and ranking showed
    deactivate A    
end 

@enduml