@startuml
scale 1024 width
scale 768 height

skinparam linetype ortho

state TOURNAMENT{
    [*] --> CREATED: Creation

    CREATED: - name set

    CREATED --> DEFINED: setting

    DEFINED: - programming language/s set
    DEFINED: - outline available
    DEFINED: - max and min number of student per team set
    DEFINED: - duration set
    DEFINED: - deadline for subscription set

    state c <<choice>>

    DEFINED --> c

    c --> EDUCATORADDED: adding educator

    EDUCATORADDED: - new educator in the tournament

    c --> BATTLECREATED: creating battle

    BATTLECREATED: - description available
    BATTLECREATED: - code available
    BATTLECREATED: - tests available
    BATTLECREATED: - automatic evaluation parameter defined
    BATTLECREATED: - [optional] manual evaluation parameter defined

    c --> BADGECREATED: defining badge

    BADGECREATED: - name set
    BADGECREATED: - rule/s defined

    EDUCATORADDED --> BATTLECREATED: creating battle
    BATTLECREATED --> EDUCATORADDED: adding educator
    EDUCATORADDED --> BADGECREATED: defining badge
    BADGECREATED --> EDUCATORADDED: adding educator
    BATTLECREATED --> BADGECREATED: defining badge
    BADGECREATED --> BATTLECREATED: creating battle

    EDUCATORADDED --> ONLINE: tournament publication
    BATTLECREATED --> ONLINE: tournament publication
    BADGECREATED --> ONLINE: tournament publication

    ONLINE: - students subscribe to the tournament in teams

    ONLINE --> STARTED: deadline for subscription met

    STARTED: - all the battles are now available
    STARTED: - tournament score and rank now available

    STARTED --> BATTLE: battles online

    state BATTLE{
        [*] --> ACCESSIBLE: RMP repo online

        ACCESSIBLE: - students do the fork of the repo
        ACCESSIBLE: - battle score available
        ACCESSIBLE: - completation status available
        ACCESSIBLE: - automatic evaluation enabled

        ACCESSIBLE --> MANUALEVALUATED: [optional] educator's evaluation

        MANUALEVALUATED: - an educator evaluate the code written

        MANUALEVALUATED --> ACCESSIBLE
        ACCESSIBLE --> CLOSED: deadline reached

        CLOSED: - it is no more possible modify the code
        CLOSED: - the battle score is ultimated

        CLOSED --> [*]
    }

    BATTLE --> OFFLINE: deadline reached

    OFFLINE: - it is no more possible complete battles
    OFFLINE: - tournament score and rank are ultimated
    OFFLINE: - badges are assigned automatically

    OFFLINE --> [*]
}

@enduml