@startuml

state TOURNAMENT{
    [*] -right-> CREATED: creation

    CREATED: - name set

    CREATED -right-> DEFINED: setting

    DEFINED: - programming language/s set
    DEFINED: - outline available
    DEFINED: - max and min number of student per team set
    DEFINED: - duration set
    DEFINED: - deadline for subscription set

    state c <<choice>>

    DEFINED -down-> c

    c -down---> EDUCATORADDED: adding educator

    EDUCATORADDED: - new educator in the tournament

    c -left-> BATTLECREATED: creating battle

    BATTLECREATED: - description available
    BATTLECREATED: - code available
    BATTLECREATED: - tests available
    BATTLECREATED: - automatic evaluation parameter defined
    BATTLECREATED: - [optional] manual evaluation parameter defined

    c -right-> BADGECREATED: defining badge

    BADGECREATED: - name set
    BADGECREATED: - rule/s defined

    EDUCATORADDED -left-> BATTLECREATED: creating battle
    BATTLECREATED -right-> EDUCATORADDED: adding educator
    EDUCATORADDED -right-> BADGECREATED: defining badge
    BADGECREATED -left-> EDUCATORADDED: adding educator
    BATTLECREATED -right-> BADGECREATED: defining badge
    BADGECREATED -left-> BATTLECREATED: creating battle

    EDUCATORADDED -down-> ONLINE: tournament publication
    BATTLECREATED -down-> ONLINE: tournament publication
    BADGECREATED -down-> ONLINE: tournament publication

    ONLINE: - students subscribe to the tournament in teams

    ONLINE --> STARTED: deadline for subscription met

    STARTED: - all the battles are now available
    STARTED: - tournament score and rank now available

    STARTED --> BATTLE: battles online

    state BATTLE{
        [*] --> ACCESSIBLE: RMP repo online

        ACCESSIBLE: - students do the fork of the repo
        ACCESSIBLE: - battle score available
        ACCESSIBLE: - completation status available
        ACCESSIBLE: - automatic evaluation enabled

        ACCESSIBLE --> MANUALEVALUATED: [optional] educator's evaluation

        MANUALEVALUATED: - an educator evaluate the code written

        MANUALEVALUATED --> ACCESSIBLE
        ACCESSIBLE -right-> CLOSED: deadline reached

        CLOSED: - it is no more possible modify the code
        CLOSED: - the battle score is ultimated

        CLOSED --> [*]
    }

    BATTLE -right-> OFFLINE: deadline reached

    OFFLINE: - it is no more possible complete battles
    OFFLINE: - tournament score and rank are ultimated
    OFFLINE: - badges are assigned automatically

    OFFLINE -right-> [*]
}

@enduml