@startuml
state TOURNAMENT{
    [*] --> DEFINED: setting

    DEFINED: - name set
    DEFINED: - programming language/s set
    DEFINED: - outline available
    DEFINED: - max number of students per team set
    DEFINED: - duration set
    DEFINED: - deadline for subscription set

    DEFINED --> CREATED: creation

    CREATED: - battle/s available
    CREATED: - [optional] badge/s available

    CREATED --> CREATED: adding educator | adding battle | adding badge

    'CREATED --> CREATED: adding educator
    'CREATED -[HIDDEN]-> CREATED: GIMMESPACEE
    'CREATED --> CREATED: adding battle
    'CREATED -[HIDDEN]-> CREATED: GIMMESPACEE
    'CREATED --> CREATED: adding badge

    CREATED --> ONLINE: tournament publication

    ONLINE: - students are notificated by email of the new tournament
    ONLINE: - students subscribe to the tournament in teams
    ONLINE --> ONLINE: adding team

    ONLINE --> STARTED: deadline for subscription met

    STARTED: - all the battles are now available
    STARTED: - tournament score and rank now available

    STARTED --> BATTLE: battles online

    state BATTLE{
        [*] -> ACCESSIBLE: RMP repo online

        ACCESSIBLE: - students do the fork of the repo
        ACCESSIBLE: - battle score available
        ACCESSIBLE: - completation status available
        ACCESSIBLE: - automatic evaluation enabled

        ACCESSIBLE -> ACCESSIBLE: [optional] manual educator's evaluation

        ACCESSIBLE --> CLOSED: deadline reached

        CLOSED: - it is no more possible modify the code
        CLOSED: - the battle score is ultimated

        CLOSED -> [*]
    }

    BATTLE --> BATTLE: update tournament scores

    BATTLE --> OFFLINE: deadline reached

    OFFLINE: - it is no more possible complete battles
    OFFLINE: - tournament score and rank are ultimated
    OFFLINE: - badges are assigned automatically
    OFFLINE: - students receive a mail with the ranking position

    OFFLINE --> [*]
}

@enduml