@startuml
'skinparam linetype polyline
left to right direction

:User: <<Human>>
rectangle Users{
    :StudentA:<<Human>>
    :EducatorA:<<Human>>
    :StudentB:<<Human>>
    :EducatorB:<<Human>>
}

rectangle Applications{
    :CodeKataBattle: as CKB <<Application>>
    :EmailProvider: as EP <<Application>>
}
usecase "Sign in" as UC1
usecase "Sign in as Student" as UC1A
usecase "Sign in as Educator" as UC1B
usecase "Invite a User" as UC3
usecase "Invite a friend to a Tournament" as UC3A
usecase "Invite a colleage to a Tournament" as UC3B


Users --|> User: extends
StudentA --> UC1A
EducatorA --> UC1B
UC1A --> UC1
UC1B --> UC1
UC1 --> CKB
StudentA --> UC3A
EducatorA --> UC3B
UC3A --> UC3
UC3B --> UC3
UC3 --> CKB

CKB -left-> EP: asks confermation throught
User -> EP: confirms its identity throught
CKB -left-> UC3
UC3 -left-> UC3A
UC3 -left-> UC3B
UC3A -> EP: sends the invitation throught
UC3B -> EP: sends the invitation throught
EP -left-> StudentB: sends the invitation to
EP -left-> EducatorB: sends the invitation to

@enduml