@startuml
skinparam linetype polyline

entity Battle {
    * battle_name
    * tournament_name
    --
    description
    rmp_repo_link
}

entity Tournament {
    * tournament_name
    --
    programming_language*
    description
    duration
    subscribe_deadline
    maximum_number_of_students_per_team
    minimum_number_of_students_per_team
    educator_rmp_handle*
}

entity Team {
    * name
    * tournament_name
    --
    students*
}

entity Badge {
    * name
    * tournament_name
    --
    description
    image
    requirements*
}

entity User {
    * email
    --
    rmp_handle [unique]
    name
    surname
    password
}

entity Student {
    --
    badges*
}

entity Educator{
}

entity Score {
}

entity BattleScore {
    * battle_name
    * team
    --
    functional_points
    timeliness_points
    quality_points
    manual_points
}

entity TournamentScore {
    * tournament_name
    * team
    --
    points
}

User <|- Educator
Student --|> User

Score <|-- BattleScore
Score <|-- TournamentScore


Tournament ||-o{ Battle: composed by
Tournament ||--o{ Badge: part of
Team }o-|| Tournament

Student }o-o{ Badge: achieve
Team }o--|{ Student: composed by

Tournament }o--|{ Educator: involved

BattleScore }o--|| Team: has
TournamentScore }o--|| Team: has
BattleScore }o--|| Battle: has
TournamentScore }o--|| Tournament: has

@enduml