@startuml

actor Student as S
participant EmailProvider as E
entity CKBPlatform as P
participant RMP as R

S--->R: pushes code
activate R
P--->R: requires code
activate P
P<---R: pulls code
deactivate R
P--->P: runs tests
activate P
deactivate P
P--->P: RMP handles and E-mail addresses to assign Badges
activate P
deactivate P
P--->P: search corresponding accounts
activate P
deactivate P
group if all commit Users correspond to CKB platform Users
    P--->E: sends E-mails to each Student in the list
    activate E
    deactivate P
    E--->S: delivers the e-mail notification to chosen Student
    deactivate E
end 

@enduml