@startuml

autonumber

actor Bob
participant EmailProvider as Email
participant CKBWebApp as App
entity CKBPlaform as Platform

activate Bob
Bob -> App: Access to platform website
activate App
App -> Platform: request login/sign in page
activate Platform
Platform --> App: login/sign in page
deactivate Platform
App --> Bob: login/sign in page
deactivate App
Bob -> App: select sign in
activate App
App -> Platform: request sign in page
activate Platform
Platform --> App: sign in page
deactivate Platform
App --> Bob: sign in page
deactivate App
Bob -> App: give name, surname, password, e-mail, RMPHandle, Educator Role
activate App
App -> Platform: sign in name, surname, password, password, e-mail
activate Platform

alt e-mail accepted
    activate Platform
    Platform --> App: Credentials accepted. Confirm registration on email submitted
    Platform -> Email: send confirmation email
    deactivate Platform
    activate Email
    Email -> Bob: confirmation link
    deactivate Email
    App --> Bob: password accepted. Confirm registration on email submitted
    deactivate App
    Bob -> Bob: click confirmation link
else e-mail already in use
    Platform --> App: email already in use
    activate App
    App --> Bob: email already in use
    deactivate App
    deactivate Bob
end

@enduml