@startuml

autonumber

actor Alice
participant EmailProvider as Email
entity CKBPlaform as Platform

activate Platform

loop on all repositories
    Platform -> Platform: runs Badge tests
end

    Platform -> Platform: search for Badge receiver

loop for each Badge assigned:
    Platform -> Platform: assign Badge to user "Alice"
    Platform -> Email: notification of obtaining the Badge
    deactivate Platform
    activate Email
    Email -> Alice: notification of obtaining the Badge
    deactivate Email
end

@enduml