@startuml
actor InvitedEducator as UB
actor InvitingEducator as UA
participant CKBWebApp as A
entity CKBPlatform as P
participant EmailProvider as E

UA--->A: clicks on "collaborate button"
activate UA
activate A
UA<---A: shows a form to fill 
UA--->A: provides infos to fill the form
UA--->A: clicks on submit button
deactivate UA
A---->P: sends the information of User to invite
deactivate A
group if wrong information is provided
    activate P
    P-->P: checks information
    note right
        Are checked e-mail address existence,
        if the User to invite is actually a registerd Educator
        and if he/she does not collaborate to the Tournament
    end note
    P-->E: sends email to inform of wrong information provided
    activate E
    E-->UA: receives notification of wrong information provided
    deactivate E
else
P---->E: sends Email to invited User
deactivate P
activate E
E---->UB: delivers invitiation Email
deactivate E
group InvitedEducator declines invitiation
    UB--->P: clicks on "Decline" button
    activate P
    P---->A: comunicates the Decline
    deactivate P
    activate A
    A---->UA: shows answer 
    deactivate A
else InvitedEducator accepts invitiation
    UB--->P: clicks on "Accept" button
    activate P
    P--->P: change permissions on a Tournament
    P---->A: comunicates the Acceptance
    deactivate P
    activate A
    A---->UA: shows answer
    deactivate A
end 
end 
@enduml