@startuml

autonumber

actor User as S
participant CKBWebApp as E
entity CKBPlatform as P

activate S
S -> E: submit user's data in the search bar
activate E
E -> P: search users with similar data
activate P
P --> E: list of found users
deactivate P
E --> S: show found users
deactivate E
S -> E: click on a user on list
activate E
E -> P: get searched user profile
activate P
P --> E: user profile data
deactivate P
E --> S: show user profile
deactivate E
deactivate S

@enduml