@startuml

actor InvitedEducator as UB
actor InvitingEducator as UA
participant EmailProvider as E
participant CKBWebApp as A
entity CKBPlatform as P

activate UA
UA -> A: insert the email of the\nInvitedEducator and clicks on "invite" button
deactivate UA
activate A
A -> P: sends the Email of Educator to invite
deactivate A
activate P
P -> P: checks Email

alt if a non valid Email is provided
    P -> E: sends Email to inform of a non valid Email provided
    deactivate P
    activate E
    E -> UA: receives notification of a non valid Email provided
    deactivate E
else if a valid Email is provided
    P -> E: sends Email to invited Educator
    activate E
    E -> UB: delivers invitiation Email
    deactivate E

    alt InvitedEducator declines invitiation
        UB -> P: clicks on "Decline" button
    else InvitedEducator accepts invitiation
        UB -> P: clicks on "Accept" button
        activate P
        P -> P: Educator added \nto the Tournament
    end
    deactivate P
end 

@enduml