@startuml
actor InvitedStudent as UB
actor InvitingStudent as UA
participant EmailProvider as E
participant CKBWebApp as A
entity CKBPlatform as P

UA--->A: clicks on "collaborate button"
activate UA
activate A
UA<---A: shows a form to fill 
UA--->A: submit the form
deactivate UA
A---->P: sends the email of Student to invite
P-->P: checks information
deactivate A
alt if a non valid email is provided
    activate P
    P-->E: sends email to inform of a non valid email provided
    activate E
    E-->UA: receives notification of a non valid email provided
    deactivate E
else if a valid email is provided
P---->E: sends Email to invited Student
deactivate P
activate E
E---->UB: delivers invitiation Email
deactivate E

alt InvitedStudent declines invitiation
    UB--->P: clicks on "Decline" button
else InvitedStudent accepts invitiation
    UB--->P: clicks on "Accept" button
    activate P
    P--->P: Adds InvitedStudent to the Team
end 
end 
@enduml