@startuml

autonumber

actor Educator as E
participant EmailProvider as EP
participant CKBWebApp as A
entity CKBPlatform as P

activate E
E -> A: clicks on "Add Badge" button
activate A
A -> P: add Badge
P --> A: return Badge creation form
E <-- A: shows Badge creation form
deactivate A
E -> A: submits the filled form
deactivate E
activate A
A -> P: sends Badge creation form compiled
deactivate A
activate P
P -> P: checks requirements script correctness

alt if script is not correct
    P -> EP: sends Email to inform of unsuccessful operation
    deactivate P
    activate EP
    E <- EP: sends Email to inform of unsuccessful operation
    deactivate EP
else if script is correct
    activate P
    P -> P: registers Badge creation
    P -> EP: send Email to inform of Badge creation
    deactivate P
    activate EP
    E <- EP: send Email to inform of Badge creation
    deactivate EP
end

@enduml