@startuml

autonumber

actor Student
participant StudentEmail
actor Educator
participant EducatorEmail as Email
participant CKBWebApp as App
entity CKBPlaform as Platform

activate Educator
Educator -> App: click on "Create Tournament" button
activate App
App -> Platform: create Tournament
activate Platform
Platform --> App: Tournament creation form
deactivate Platform
App --> Educator: Tournament creation form
deactivate App
Educator -> App: submit form filled with Tournament's information
activate App
App -> Platform: form filled with Tournament's information
activate Platform
Platform -> Platform: registers \nTournament \ncreation
Platform -> Email: Tournament creation confermation
activate Email
Platform --> App: return new Tournament's homepage
deactivate Platform
Email -> Educator: Tournament creation confermation
deactivate Email
App --> Educator: new Tournament's homepage
deactivate App
deactivate Educator

loop to each student subscribed to CKB
    Platform -> StudentEmail: new Tournament available + link
    activate StudentEmail
    StudentEmail -> Student: new Tournament available + link
    deactivate StudentEmail
end

@enduml