@startuml

autonumber

actor Alice
participant EmailProvider as Email
participant CKBWebApp as App
entity CKBPlaform as Platform

activate Alice
Alice -> App: access to platform website
activate App
App -> Platform: request login/sign in page
activate Platform
Platform --> App: login/sign in page
deactivate Platform
App --> Alice: login/sign in page
deactivate App
Alice -> App: select sign in
activate App
App -> Platform: request sign in page
activate Platform
Platform --> App: sign in page
deactivate Platform
App --> Alice: sign in page
deactivate App
Alice -> App: select student
activate App
App -> Platform: request student sign in page
activate Platform
Platform --> App: student sign in page
deactivate Platform
App --> Alice: student sign in page
deactivate App
Alice -> App: give name, surname, e-mail and RMP handle
activate App
App -> Platform: sign in name, surname, e-mail and RMP handle
activate Platform

alt e-mail accepted
    Platform --> App: create a password
    deactivate Platform
    App --> Alice: create a password
    deactivate App
    Alice -> App: new password
    activate App
    App -> Platform: new password
    activate Platform
    Platform --> App: password accepted. Confirm registration on email submitted
    Platform -> Email: send confirmation email
    deactivate Platform
    activate Email
    Email -> Alice: confirmation link
    deactivate Email
    App --> Alice: password accepted. Confirm registration on email submitted
    deactivate App
    Alice -> Alice: click confirmation link
else e-mail already in use
    Platform --> App: email already in use
    activate App
    App --> Alice: email already in use
    deactivate App
    deactivate Alice
end

@enduml