@startuml

autonumber

actor Educator
participant EmailProvider as Email
participant CKBWebApp as App
entity CKBPlaform as Platform

activate Educator
Educator -> App: clicks on "Add battle" button
activate App
App -> Platform: Add battle
activate Platform
Platform --> App: Battle creation form
deactivate Platform
App --> Educator: Battle creation form
deactivate App
Educator -> App: submit form filled with name, overview and RMP repo link
activate App
App -> Platform: form filled with name, overview and RMP repo link
activate Platform
Platform -> Platform: battle registered to tournament
Platform -> Email: Battle creation confermation
activate Email
Platform --> App: return new battle's homepage
deactivate Platform
Email -> Educator: Battle creation confermation
deactivate Email
App --> Educator: new battle's homepage
deactivate App
Educator -> App: defines evaluation modalities
deactivate Educator
activate App
App -> Platform: evaluation modalities
deactivate App
activate Platform
Platform -> Platform: sets the evaluation parameter

@enduml