@startuml

autonumber

actor Educator
participant EmailProvider as Email
participant CKBWebApp as App
entity CKBPlaform as Platform

activate Educator
Educator -> App: Create Tournament
activate App
App -> Platform: Create Tournament
activate Platform
Platform -> App: Tournament creation form
deactivate Platform
App -> Educator: Tournament creation form
deactivate App
Educator -> App: Form filled with name, programming language/s and overview
activate App
App -> Platform: Form filled with name, programming language/s and overview
activate Platform
Platform -> Platform: Registers tournament creation
Platform -> App: Tournament created
Platform -> Email: Tournament creation confermation 
activate Email
deactivate Platform
App -> Educator: Tournament created
deactivate App
Email -> Educator: Tournament creation confermation 
deactivate Email
deactivate Educator
note right
    da sistemare bisogna aggiungere l'invio delle mail agli studenti, bisogna aggiungere quello che riguarda i team min max duration deadline to subscribe
end note
@enduml