@startuml

autonumber

actor Student
participant StudentEmail
actor Educator
participant EducatorEmail as Email
participant CKBWebApp as App
entity CKBPlaform as Platform

activate Educator
Educator -> App: click on "Create tournament" button
activate App
App -> Platform: create tournament
activate Platform
Platform --> App: tournament creation form
deactivate Platform
App --> Educator: tournament creation form
deactivate App
Educator -> App: submit form filled with tournament's information
activate App
App -> Platform: form filled with tournament's information
activate Platform
Platform -> Platform: registers tournament creation
Platform -> Email: tournament creation confermation
activate Email
Platform --> App: return new tournament's homepage
deactivate Platform
Email -> Educator: tournament creation confermation
deactivate Email
App --> Educator: new tournament's homepage
deactivate App
deactivate Educator

loop to each student subscribed to CKB
    Platform -> StudentEmail: new tournament available + link
    activate StudentEmail
    StudentEmail -> Student: new tournament available + link
    deactivate StudentEmail
end

@enduml