@startuml

autonumber

actor Alice
participant EmailProvider as Email
entity CKBPlaform as Platform

activate Platform

loop on all repositories
    Platform -> Platform: runs badge tests
end

    Platform -> Platform: search for badge receicever

loop for each badge assigned:
    Platform -> Platform: assign badge to user "Alice"
    Platform -> Email: notification of obtaining the badge
    deactivate Platform
    activate Email
    Email -> Alice: notification of obtaining the badge
    deactivate Email
end

@enduml