@startuml

autonumber

entity CKBPlatform as P
participant RMP as R

activate R
R -> P: call the API
deactivate R
activate P
P -> P: checks repository link

alt Team owner of the repository is recognized
    P -> R: pulls code
    activate R
    R --> P: returns the code
    deactivate R
    P -> R: pulls Educator code
    activate R
    R --> P: returns the code
    deactivate R
    P -> P: creates new test environment instance
    P -> P: inserts Team code inside test environment
    P -> P: runs automatic tests inside environment
    P -> P: update Team's battle score 
    P -> P: update Team's Tournament score
else repository is not associated to any team
end
deactivate P

@enduml