@startuml

autonumber

actor Educator
participant EmailProvider as Email
participant CKBWebApp as App
entity CKBPlaform as Platform

activate Educator
Educator -> App: clicks on "Add Battle" button
activate App
App -> Platform: Add Battle
activate Platform
Platform --> App: Battle creation form
deactivate Platform
App --> Educator: Battle creation form
deactivate App
Educator -> App: submit form filled with name, overview, RMP repo link and evaluation modalities
activate App
App -> Platform: form filled with name, overview, RMP repo link and evaluation parameters
activate Platform
Platform -> Platform: Battle registered \nto Tournament
Platform -> Email: Battle creation confermation
activate Email
Platform --> App: return new Battle's homepage
deactivate Platform
Email -> Educator: Battle creation confermation
deactivate Email
App --> Educator: new Battle's homepage
deactivate App

@enduml