@startuml
actor InvitedUser as UB
actor InvitingUser as UA
participant EmailProvider as E
participant CKBWebApp as A
entity CKBPlatform as P

UA--->A: clicks on "collaborate button"
activate UA
activate A
UA<---A: shows a form to fill 
UA--->A: provides infos to fill the form
UA--->A: clicks on submit button
deactivate UA
A---->P: sends the information of User to invite
deactivate A
group if wrong information is provided
    activate P
    P-->P: checks information
    P-->E: sends email to inform of wrong information provided
    activate E
    E-->UA: receives notification of wrong information provided
    deactivate E
else
P---->E: sends Email to invited User
deactivate P
activate E
E---->UB: delivers invitiation Email
deactivate E
group InvitedUser declines invitiation
    UB--->P: clicks on "Decline" button
    activate P
    P---->A: comunicates the Decline
    deactivate P
    activate A
    A---->UA: shows answer 
    deactivate A
else InvitedStudent accepts invitiation
    UB--->P: clicks on "Accept" button
    activate P
    group Users are Educators
        P--->P: manage Tournament permissions
    else Users are Students
        P--->P: creates a Team 
    end
    P---->A: comunicates the Acceptance
    deactivate P
    activate A
    A---->UA: shows answer
    deactivate A
end 
end 
@enduml